-- ============================================================
-- Museums Table - 10 New INSERT Statements
-- CategoryId Reference: 1=Archaeology, 2=Art, 3=Ethnography
-- 4=Ancient City, 5=Ancient Theater, 6=Temple Ruins
-- IDs start at 4 (1-3 already exist in the database)
-- NOTE: All Wikimedia Commons URLs should be verified at
--       commons.wikimedia.org before deploying to production.
-- ============================================================

INSERT INTO dbo.Museums (MuseumId, MuseumName, City, District, Address, Description, ImageUrl, TicketPrice, OpeningHours, PhoneNumber, Email, Website, IsFeatured, IsActive, CreatedDate, UpdatedDate, CategoryId, GoogleMapsUrl)
VALUES
(
    4,
    N'Museum of Anatolian Civilizations',
    N'Ankara',
    N'Altındağ',
    N'Gözcü Sk. No:2, 06240 Altındağ/Ankara',
    N'One of the world''s most important archaeological museums, housed in a restored 15th-century bedesten and caravanserai. The collection spans from the Paleolithic Age to the Roman period, with an unrivalled Hittite and Phrygian artifacts gallery including the famous Hittite sun discs and sphinx statues from Alacahöyük and Hattusa.',
    N'https://upload.wikimedia.org/wikipedia/commons/f/f9/Ankara_Anadolu_Medeniyetleri_M%C3%BCzesi.jpg',
    200.00,
    N'08:30 - 19:30 (Apr–Oct), 08:30 - 17:30 (Nov–Mar)',
    N'+90 312 324 31 60',
    N'anadolumedeniyetleri@ktb.gov.tr',
    N'https://muze.gov.tr',
    1,
    1,
    '2024-01-01 00:00:00',
    NULL,
    1,
    N'https://maps.google.com/?q=Museum+of+Anatolian+Civilizations+Ankara'
),
(
    5,
    N'Topkapı Palace Museum',
    N'İstanbul',
    N'Fatih',
    N'Cankurtaran Mh., 34122 Fatih/İstanbul',
    N'The primary administrative center of the Ottoman Empire for nearly four centuries, now one of the most visited museums in the world. Its treasures include the imperial Harem, the Topkapı Dagger, the Spoonmaker''s Diamond, Chinese and Japanese porcelain collections, Ottoman miniatures, and sacred relics of the Prophet Muhammad.',
    N'https://upload.wikimedia.org/wikipedia/commons/e/e5/Topkapi_palace.jpg',
    750.00,
    N'09:00 - 18:45 (Closed Tuesday)',
    N'+90 212 512 04 80',
    N'topkapi@millisaraylar.gov.tr',
    N'https://topkapisarayi.gov.tr',
    1,
    1,
    '2024-01-01 00:00:00',
    NULL,
    2,
    N'https://maps.google.com/?q=Topkapi+Palace+Museum+Istanbul'
),
(
    6,
    N'Mevlana Museum',
    N'Konya',
    N'Karatay',
    N'Aziziye Mh., Mevlana Cd. No:1, 42030 Karatay/Konya',
    N'Formerly the lodge of the Mevlevi order of Sufism, this museum is built around the mausoleum of 13th-century poet and mystic Jalal ad-Din Muhammad Rumi (Mevlana). Its iconic turquoise-tiled conical dome is one of Turkey''s most recognizable landmarks. The museum displays original manuscripts, musical instruments, prayer rugs, and personal belongings of Rumi and his followers.',
    N'https://upload.wikimedia.org/wikipedia/commons/d/d0/Mevlana_Museum.jpg',
    100.00,
    N'09:00 - 17:30',
    N'+90 332 351 12 15',
    NULL,
    N'https://muze.gov.tr',
    1,
    1,
    '2024-01-01 00:00:00',
    NULL,
    3,
    N'https://maps.google.com/?q=Mevlana+Museum+Konya'
),
(
    7,
    N'Troy Museum',
    N'Çanakkale',
    N'Merkez',
    N'Tevfikiye Köyü, 17100 Çanakkale/Çanakkale',
    N'Opened in 2018, this state-of-the-art museum is located at the gates of the UNESCO World Heritage Site of ancient Troy (Hisarlik). It displays over 40,000 artifacts spanning nine successive civilizations, from the Bronze Age to the Byzantine period. Highlights include gold jewelry, terracotta figurines, weapons, and a faithful replica of the legendary Trojan Horse.',
    N'https://upload.wikimedia.org/wikipedia/commons/a/a7/Troya_M%C3%BCzesi.jpg',
    200.00,
    N'08:00 - 19:00 (Apr–Oct), 08:00 - 17:00 (Nov–Mar)',
    N'+90 286 283 06 36',
    NULL,
    N'https://muze.gov.tr',
    0,
    1,
    '2024-01-01 00:00:00',
    NULL,
    1,
    N'https://maps.google.com/?q=Troy+Museum+Canakkale'
),
(
    8,
    N'Pera Museum',
    N'İstanbul',
    N'Beyoğlu',
    N'Meşrutiyet Cd. No:65, 34430 Tepebaşı/Beyoğlu/İstanbul',
    N'A distinguished private museum in the heart of Beyoğlu, founded by the Suna and İnan Kıraç Foundation. It is home to three core permanent collections: Orientalist Paintings, Anatolian Weights and Measures, and Kütahya Tiles and Ceramics. It is also internationally acclaimed for hosting major travelling exhibitions from leading global museums such as the Hermitage and the Louvre.',
    N'https://upload.wikimedia.org/wikipedia/commons/5/5e/Pera_Museum_Istanbul.jpg',
    280.00,
    N'10:00 - 19:00 (Tue–Sat), 12:00 - 18:00 (Sun, Closed Monday)',
    N'+90 212 334 99 00',
    N'info@peramuzesi.org.tr',
    N'https://www.peramuzesi.org.tr',
    0,
    1,
    '2024-01-01 00:00:00',
    NULL,
    2,
    N'https://maps.google.com/?q=Pera+Museum+Beyoglu+Istanbul'
),
(
    9,
    N'Bodrum Museum of Underwater Archaeology',
    N'Muğla',
    N'Bodrum',
    N'Bodrum Kalesi, 48400 Bodrum/Muğla',
    N'One of the world''s foremost underwater archaeology museums, dramatically situated within the 15th-century crusader Castle of St. Peter. Its collection includes artifacts from ancient shipwrecks recovered from the Aegean and Mediterranean seabeds, most notably the Late Bronze Age Uluburun Shipwreck (c. 1300 BC) — the oldest fully excavated shipwreck in history — and the 11th-century Glass Wreck.',
    N'https://upload.wikimedia.org/wikipedia/commons/b/b4/Bodrum_kalesi.jpg',
    150.00,
    N'08:30 - 17:00 (Closed Monday)',
    N'+90 252 316 25 16',
    NULL,
    N'https://muze.gov.tr',
    1,
    1,
    '2024-01-01 00:00:00',
    NULL,
    1,
    N'https://maps.google.com/?q=Bodrum+Museum+of+Underwater+Archaeology'
),
(
    10,
    N'Hatay Archaeology Museum',
    N'Hatay',
    N'Antakya',
    N'Gündüz Cad. No:1, 31040 Antakya/Hatay',
    N'Widely regarded as one of the finest mosaic museums in the world, this museum houses an extraordinary collection of Roman and Byzantine mosaics excavated from ancient Antioch on the Orontes and its surroundings. Covering thousands of square meters of floor space, its mosaics date primarily from the 2nd to 5th centuries AD. The museum also holds artifacts from Prehistoric, Hittite, Assyrian, Persian, Hellenistic, and Roman periods.',
    N'https://upload.wikimedia.org/wikipedia/commons/9/9e/Hatay_Arkeoloji_M%C3%BCzesi.jpg',
    200.00,
    N'08:30 - 17:30',
    N'+90 326 214 61 68',
    NULL,
    N'https://muze.gov.tr',
    0,
    1,
    '2024-01-01 00:00:00',
    NULL,
    1,
    N'https://maps.google.com/?q=Hatay+Archaeology+Museum+Antakya'
),
(
    11,
    N'Rahmi M. Koç Museum',
    N'İstanbul',
    N'Beyoğlu',
    N'Hasköy Cad. No:5, 34445 Hasköy/Beyoğlu/İstanbul',
    N'Turkey''s leading industrial museum, situated on the scenic Golden Horn waterfront. Housed in a beautifully restored 19th-century Ottoman anchor factory and an adjacent historic building, the museum chronicles the history of transportation, industry, and communications. Its extensive collection spans vintage automobiles, steam locomotives, aircraft, submarines, nautical vessels, scientific instruments, and toy collections.',
    N'https://upload.wikimedia.org/wikipedia/commons/4/4c/Rahmi_M_Ko%C3%A7_Museum.jpg',
    250.00,
    N'10:00 - 17:00 (Tue–Fri), 10:00 - 19:00 (Sat–Sun, Closed Monday)',
    N'+90 212 369 66 00',
    N'info@rmk-museum.org.tr',
    N'https://www.rmk-museum.org.tr',
    0,
    1,
    '2024-01-01 00:00:00',
    NULL,
    2,
    N'https://maps.google.com/?q=Rahmi+M+Koc+Museum+Istanbul'
),
(
    12,
    N'Çorum Hittite Museum',
    N'Çorum',
    N'Merkez',
    N'İnönü Cad., 19100 Merkez/Çorum',
    N'Houses one of Turkey''s most significant Hittite artifact collections, featuring finds from the UNESCO World Heritage Sites of Hattusa (Boğazköy) and Alacahöyük. Key exhibits include the iconic Hittite bronze solar discs, sphinx statues, cuneiform clay tablets, ceremonial standards, and a rich variety of bronze weapons and pottery spanning the 3rd–1st millennia BC.',
    N'https://upload.wikimedia.org/wikipedia/commons/2/2c/%C3%87orum_M%C3%BCzesi.jpg',
    100.00,
    N'08:30 - 17:30',
    N'+90 364 213 11 67',
    NULL,
    N'https://muze.gov.tr',
    0,
    1,
    '2024-01-01 00:00:00',
    NULL,
    1,
    N'https://maps.google.com/?q=Corum+Hittite+Museum'
),
(
    13,
    N'Ankara Ethnography Museum',
    N'Ankara',
    N'Altındağ',
    N'Talat Paşa Blv. No:11, 06110 Altındağ/Ankara',
    N'Established in 1930 by Atatürk to preserve Turkish and Ottoman cultural heritage, this museum was itself used as a temporary resting place for Atatürk''s catafalque until the completion of Anıtkabir in 1953. Its rich collection includes Ottoman court costumes, Anatolian carpets and kilims, hand-embroidered textiles, calligraphic manuscripts, weapons, inlaid woodwork, Çanakkale ceramics, and silverware.',
    N'https://upload.wikimedia.org/wikipedia/commons/7/73/Etnografya_M%C3%BCzesi_Ankara.jpg',
    80.00,
    N'08:30 - 17:30 (Closed Monday)',
    N'+90 312 311 95 56',
    NULL,
    N'https://muze.gov.tr',
    0,
    1,
    '2024-01-01 00:00:00',
    NULL,
    3,
    N'https://maps.google.com/?q=Ankara+Ethnography+Museum'
);