INSERT INTO dbo.Museums
(
    MuseumName,
    City,
    District,
    Address,
    Description,
    ImageUrl,
    TicketPrice,
    OpeningHours,
    PhoneNumber,
    Email,
    Website,
    IsFeatured,
    IsActive,
    CreatedDate,
    UpdatedDate,
    CategoryId,
    GoogleMapsUrl
)
VALUES

(
    N'Museum of Anatolian Civilizations',
    N'Ankara',
    N'Altindag',
    N'Gozcu Sok. No:2, Altindag/Ankara',
    N'One of Turkey''s most important archaeology museums featuring Hittite, Phrygian and Roman artifacts.',
    N'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?q=80&w=1200&auto=format&fit=crop',
    200.00,
    N'08:30 - 19:30',
    N'+90 312 324 31 60',
    N'anadolumedeniyetleri@ktb.gov.tr',
    N'https://muze.gov.tr',
    1,
    1,
    GETDATE(),
    NULL,
    1,
    N'https://maps.google.com/?q=Ankara+Museum'
),

(
    N'Topkapi Palace Museum',
    N'Istanbul',
    N'Fatih',
    N'Cankurtaran Mah. Fatih/Istanbul',
    N'Historic Ottoman palace museum featuring imperial collections and sacred relics.',
    N'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=1200&auto=format&fit=crop',
    750.00,
    N'09:00 - 18:45',
    N'+90 212 512 04 80',
    N'topkapi@millisaraylar.gov.tr',
    N'https://topkapisarayi.gov.tr',
    1,
    1,
    GETDATE(),
    NULL,
    2,
    N'https://maps.google.com/?q=Topkapi+Palace+Museum'
),

(
    N'Mevlana Museum',
    N'Konya',
    N'Karatay',
    N'Aziziye Mah. Mevlana Cad.',
    N'Museum and mausoleum of Mevlana Jalaluddin Rumi.',
    N'https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=1200&auto=format&fit=crop',
    100.00,
    N'09:00 - 17:30',
    N'+90 332 351 12 15',
    NULL,
    N'https://muze.gov.tr',
    1,
    1,
    GETDATE(),
    NULL,
    3,
    N'https://maps.google.com/?q=Mevlana+Museum'
),

(
    N'Troy Museum',
    N'Canakkale',
    N'Merkez',
    N'Tevfikiye Koyu Canakkale',
    N'Modern museum presenting artifacts from ancient Troy civilization.',
    N'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&auto=format&fit=crop',
    200.00,
    N'08:00 - 19:00',
    N'+90 286 283 06 36',
    NULL,
    N'https://muze.gov.tr',
    0,
    1,
    GETDATE(),
    NULL,
    1,
    N'https://maps.google.com/?q=Troy+Museum'
),

(
    N'Pera Museum',
    N'Istanbul',
    N'Beyoglu',
    N'Mesrutiyet Cad. No:65 Beyoglu/Istanbul',
    N'Private art museum with Orientalist paintings and temporary exhibitions.',
    N'https://images.unsplash.com/photo-1566127992631-137a642a90f4?q=80&w=1200&auto=format&fit=crop',
    280.00,
    N'10:00 - 19:00',
    N'+90 212 334 99 00',
    N'info@peramuzesi.org.tr',
    N'https://www.peramuzesi.org.tr',
    0,
    1,
    GETDATE(),
    NULL,
    2,
    N'https://maps.google.com/?q=Pera+Museum'
);